version: '3'

services:
  web:
    image: main:latest
    ports:
      - "8000:8000"
#    depends_on:
#      - db
    environment:
      - DJANGO_SETTINGS_MODULE=web.production
    command: gunicorn web.wsgi:application -b 0.0.0.0:8000


